CREATE TABLE USDJPY_RATE_RAW_1MIN (
	DATE int(8) NOT NULL,
	TIME int(4) NOT NULL,
	WDAY varchar(3) NOT NULL,
	OPN_RATE DECIMAL(8, 4) NOT NULL,
	HGHT_PRC DECIMAL(8, 4) NOT NULL,
	LW_PRC DECIMAL(8, 4) NOT NULL,
	CLS_RATE DECIMAL(8, 4) NOT NULL,
	TRGT_FLG int(1),
	ACT int(2),
	PRIMARY KEY(DATE, TIME)
);
