CREATE TABLE USDJPY_RATE_W_RAW_1MIN (
	STEP int(10) NOT NULL,
	DATE int(8) NOT NULL,
	TIME int(4) NOT NULL,
	WDAY varchar(3) NOT NULL,
	OPN_RATE DECIMAL(8, 4) NOT NULL,
	HGHT_PRC DECIMAL(8, 4) NOT NULL,
	LW_PRC DECIMAL(8, 4) NOT NULL,
	CLS_RATE DECIMAL(8, 4) NOT NULL,
	ACT int(2),
	ASSETS DECIMAL(10,5),
	PRIMARY KEY(STEP)
);
